### PR TITLE
be compatible with yesod 1.4.*

### PR DESCRIPTION
**Pull request by CindyLinz**
Hi~ ^^
I've made some change, to made this package comatible with Yesod 1.4.*.

BTW. I didn't touched the version number of this package.

### CODE REVIEW

**Comment by TobyGoodwin** [comment]
Thanks for this! The patch looks good as far as I can tell, although currently my only yesod-auth-bcrypt using project has not been converted to yesod-1.4.

Note that I am not the maintainer of the hackage version of the package (and this is not the git tree that it is built from). I'll make this into a PR against upstream...

Thanks again!

**Comment by CindyLinz** [comment]
Oh.. Then.. Why the [hackage page](http://hackage.haskell.org/package/yesod-auth-bcrypt) said you were the uploader, and pointed to your git repository? XD

**Comment by TobyGoodwin** [comment]
Hi Cindy,

> Oh.. Then.. Why the [hackage page](http://hackage.haskell.org/package/yesod-auth-bcrypt) said you were the uploader, and pointed to your git repository? XD

Errm, because I am? Sorry, I'd completely forgotten that Ollie made me an uploader, and indeed that I uploaded the previous version.

I've now uploaded 0.2.0 including your fixes. Please let me know of any problems. And thanks so much for the patch!

Regards,

Toby.

**Comment by CindyLinz** [comment]
It works! Thank you ^^

**Pull request merged**
